name: device_vitals_app
description: "Device Vitals - Flutter app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.0.1
  injectable: ^2.5.0
  get_it: ^8.0.3
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  percent_indicator: ^4.2.5
  intl: ^0.20.2
  retrofit: ^4.8.0
  json_annotation: ^4.9.0
  device_info_plus: ^12.3.0
  syncfusion_flutter_charts: ^31.1.19
  hive_ce: ^2.13.2
  hive_ce_flutter: ^2.3.2
  workmanager: ^0.9.0+3
  path_provider: ^2.1.5
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.5.1
  build_runner: ^2.5.0
  retrofit_generator: ^10.1.0
  json_serializable: ^6.9.0
  hive_ce_generator: ^1.9.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
